### ISSUE TITLE
Supplement Xnumon, auditd, and Sysmon with {Audit,Winlog,File}beat?

### ISSUE THREAD

**Issue by peasead** [randomuserid/Tylium#1]
Do you think that Auditbeat/Filebeat/Winlogbeat has the extensibility to replace Xnumon, Auditd, and/or Sysmon?

I see your Logstash pipelines are doing some filtering, I wonder if that could be simplified with the Suricata, Nginx, etc. modules (although there are not modules for them all).

Thinking out loud, the data is going into Logstash and then Elasticsearch, I wonder if it might simplify the project to use a Beat to go directly into Elasticsearch where possible? Additionally, the "turnkey" ECS benefits would be present as well.

Cool project and I'm down to help if there's some work I can lean into.

**Comment by randomuserid** [comment]
Hi, yes, I used to use logstash with

**Comment by randomuserid** [comment]
Hey sorry I meant to reply here. So yes, I have migrated from go-audit to Auditbeat. Pretty much always used Winlogbeat for the last 2 years. I am currently working on expanding manifests for these and others in order to generate the many events needed for ATT&CK searches and hunts.Absolutely open to help with any of this or other SpaceCake work.

 I have largely moved away from Logstash to direct ES inputs via beats and filebeat modules; I needed Logstash when I was using things like go-audit. Logstash is still used for things like Suricata / Zeek at great scale but there are projects making ECS ready Logstash pipelines. 

AFA the Mac, the best source of MacOS events, in my opinion, is going to be the Elastic Endpoint agent.
